### PR TITLE
Change Windows target

### PR DESCRIPTION
**Pull request by rashil2000**
MSVC is the default recommended toolchain for Windows.

| . | Before        | After       |
| ---: | --------: | ---------: |
| Binary size | 7.74MB | 1.82MB   |
| Build time | 3m49s | 2m21s   |

### CODE REVIEW

**Comment by rashil2000** [comment]
If you'd like, you can edit your current release and put this file instead - https://github.com/rashil2000/rpg-cli/releases/download/1.0.0/rpg-cli-1.0.0-windows.exe

(It was generated through GitHub Actions in my fork, you can see the run here - https://github.com/rashil2000/rpg-cli/runs/3570036258?check_suite_focus=true)

**Comment by facundoolano** [comment]
I originally used that when I first tried to target windows, but the resulting exe didn't seem to work when I tried it in a windows machine. Have you actually tested the game after generating that artifact?

**Comment by rashil2000** [comment]
Hey, yes, I ran the executable and runs fine. Do you want me to run anything specific (where it failed for you)?

**Comment by facundoolano** [comment]
I don't remember the exact error I saw (I'm not a Windows user). I'll take some time to test again and consider merging this.

**Comment by rashil2000** [comment]
Hey @facundoolano :)
Any updates on this?

**Pull request closed without merging**
