### PR TITLE
Add fish shell example

### PR DESCRIPTION
**Pull request by pakoito**
As per title

### CODE REVIEW

**Comment by facundoolano** [comment]
thanks!

**Comment by joshmuente** [comment]
for me the example is not working correctly... my version looks like this:

```
# This helper is used to make the pwd match the tracked internally by the game
function sync_rpg
    builtin cd (rpg-cli pwd)
end

# Use the rpg as the command to do non fs related tasks such as print
# status and buy items.
function rpg
    rpg-cli $argv
    sync_rpg
end

# Try to move the hero to the given destination, and cd match the shell pwd
# to that of the hero's location:
# - the one supplied as parameter, if there weren't any battles
# - the one where the battle took place, if the hero wins
# - the home dir, if the hero dies
function cd
  if count $argv > /dev/null
      rpg-cli cd "$argv"
  else
      rpg-cli cd $HOME
  end
  sync_rpg
end

# Some directories have hidden treasure chests that you can find with ls
function ls
  if count $argv > /dev/null
      rpg-cli cd -f $argv[1]
      rpg-cli ls
      command ls $argv[1]
      rpg-cli cd (pwd)
  else
      rpg-cli ls
      command ls
  end
end
```

**Comment by facundoolano** [comment]
@joshmuente can you elaborate what wasn't working for you? do you mind sending a PR to replace the code?

**Comment by joshmuente** [comment]
@facundoolano Ok I will send a PR.
The ls function doesn't work and the cd command doesn't work without an argument

**Comment by joshmuente** [comment]
actually both functions doesn't work without an argument... also the ls function is running rpg-cli ls on the wrong directory

**Comment by joshmuente** [comment]
related https://github.com/facundoolano/rpg-cli/pull/125

**Pull request merged**
